In [1]:
import numpy as np
dataset_filename = 'affinity_dataset.txt'
X = np.loadtxt(dataset_filename)

ImportError: No module named 'numpy'

In [2]:
import numpy

ImportError: No module named 'numpy'

In [4]:
import numpy as np 
dataset_filename = "affinity_dataset.txt"
X = np.loadtxt(dataset_filename)
print(X[:50])

[[ 0.  0.  1.  1.  1.]
 [ 1.  1.  0.  1.  0.]
 [ 1.  0.  1.  1.  0.]
 [ 0.  0.  1.  1.  1.]
 [ 0.  1.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 0.  0.  0.  1.  1.]
 [ 0.  0.  1.  1.  1.]
 [ 1.  1.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  1.  0.  1.]
 [ 0.  1.  0.  0.  1.]
 [ 0.  0.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 0.  0.  1.  1.  1.]
 [ 1.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  1.]
 [ 0.  0.  1.  1.  1.]
 [ 0.  0.  1.  1.  0.]
 [ 0.  0.  1.  0.  1.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  1.  0.  1.  0.]
 [ 1.  1.  1.  0.  1.]
 [ 1.  1.  0.  0.  1.]
 [ 0.  0.  1.  1.  1.]
 [ 0.  0.  1.  0.  1.]
 [ 0.  0.  1.  1.  1.]
 [ 0.  0.  1.  1.  0.]
 [ 0.  1.  1.  0.  1.]
 [ 0.  0.  1.  1.  0.]
 [ 0.  1.  0.  0.  1.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  1.  0.  1.]
 [ 1.  1.  0.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 0.  0.  